uploadCellrangerUI <- function(id) {
  ns <- NS(id)
  fluidRow(
    column(6,
      offset = 1,
      tags$div(
        style = "border: 0.5px solid #000; padding: 10px;",
        tags$p("Please upload the filtered_feature_bc_matrix.h5 file generated by cellranger. You can optionally upload the T cell receptor file (filtered_contig_annotations.csv) and/or the B cell receptor file (filtered_contig_annotations.csv)."),
        tags$p("After uploading, click the Run button.")
      ),
      tags$div(style = "margin-top: 10px;"),
      fileInput(ns("h5"), "1. Choose .h5  file"),
      fileInput(ns("tcr"), "2. Choose .tcr file (optional)"),
      fileInput(ns("bcr"), "3. Choose .bcr file (optional)"),
      actionButton(ns("run"), "Run"),
      tags$p(id = ns("run_started_status"), style = "color: lightgray;", "Run started"),
      tags$p(id = ns("run_finished_status"), style = "color: lightgray;", "Run finished")
    ),
  )
}



uploadCellrangerServer <- function(id, myReactives) {
  moduleServer(id, function(input, output, session) {
    # これは本番用
    # observeEvent(input$run, {
    #   myReactives <- fileUpload(input, myReactives)
    # })


    # base_path <- "/Users/masakazu/Google Drive/マイドライブ/SiCR/example"
    # myReactives$h5_path <- file.path(base_path, "230405_ruft_hcw_vaccine_merge_3000.h5")
    # myReactives$tcr_path <- file.path(base_path, "230405_ruft_hcw_vaccine_merge_3000_t.csv")
    # myReactives$bcr_path <- file.path(base_path, "230405_ruft_hcw_vaccine_merge_3000_b.csv")


    observeEvent(myReactives$h5_path, {
      myReactives <- h5_to_seurat_object(myReactives)
      myReactives <- run_seurat_object(myReactives)
      myReactives <- addCelltype(myReactives)
    })

    observeEvent(myReactives$tcr_path, {
      # Seuratオブジェクトが存在することを確認
      req(myReactives$seurat_object)
      myReactives$tcr_df <- tcr_csv_to_dataframe(myReactives$tcr_path)
      myReactives$tcr_df <- myReactives$tcr_df %>% dplyr::filter(barcode %in% myReactives$seurat_object@meta.data$barcode)
      metadata <- myReactives$seurat_object@meta.data %>% select(sample, seurat_clusters, barcode)
      myReactives$tcr_df <- dplyr::left_join(myReactives$tcr_df, metadata, by = "barcode")
      saveRDS(myReactives$tcr_df, 'tcr_df.rds')
      write.csv(myReactives$tcr_df, 'tcr_df.csv', row.names= F, quote = F)
    })


    # BCRファイルのパスが変更されたときの処理
    observeEvent(myReactives$bcr_path, {
      # Seuratオブジェクトが存在することを確認
      req(myReactives$seurat_object)
      myReactives$bcr_df <- bcr_csv_to_dataframe(myReactives$bcr_path)
      myReactives$bcr_df <- myReactives$bcr_df %>% dplyr::filter(barcode %in% myReactives$seurat_object@meta.data$barcode)
      metadata <- myReactives$seurat_object@meta.data %>% select(sample, seurat_clusters, barcode)
      myReactives$bcr_df <- dplyr::left_join(myReactives$bcr_df, metadata, by = "barcode")
      saveRDS(myReactives$bcr_df, 'bcr_df.rds')
      write.csv(myReactives$bcr_df, 'bcr_df.csv',  row.names= F, quote = F)
      save(myReactives, file = "filename.RData")
    }) 
  })
}
