# --- UIの定義: uploadCellrangerUI ---
uploadCellrangerUI <- function(id) {
  ns <- NS(id)
  fluidRow(
    column(5,
      offset = 0,
      shinyjs::useShinyjs(),
      
      tags$div(
        style = "border: 0.5px solid #000; padding: 10px;",
        tags$p("Please upload either the filtered_feature_bc_matrix.h5 file generated by cellranger OR a pre-processed Seurat object (.rds). You can optionally upload the T cell receptor file (filtered_contig_annotations.csv) and/or the B cell receptor file (filtered_contig_annotations.csv)."),
        tags$p("After uploading, click the Run button.")
      ),
      tags$div(style = "margin-top: 10px;"),
      
      radioButtons(ns("datatype"), "1. Input RNA Data Type", choices = c("10X CellRanger (.h5)" = "h5", "Pre-processed Seurat Object (.rds)" = "rds"), selected = "h5"),
      
      conditionalPanel(
        condition = "input.datatype == 'h5'",
        ns = ns,
        fluidRow(
          column(8, fileInput(ns("h5"), "Choose .h5 file", accept = c(".h5"))),
          column(4, style = "margin-top: 25px;", uiOutput(ns("h5_status_ui")))
        )
      ),
      conditionalPanel(
        condition = "input.datatype == 'rds'",
        ns = ns,
        fluidRow(
          column(8, fileInput(ns("rds"), "Choose Seurat .rds file", accept = c(".rds"))),
          column(4, style = "margin-top: 25px;", uiOutput(ns("rds_status_ui")))
        )
      ),
      
      fluidRow(
        column(8, fileInput(ns("tcr"), "2. Choose .tcr file (optional)")),
        column(4, style = "margin-top: 25px;", uiOutput(ns("tcr_status_ui")))
      ),
      fluidRow(
        column(8, fileInput(ns("bcr"), "3. Choose .bcr file (optional)")),
        column(4, style = "margin-top: 25px;", uiOutput(ns("bcr_status_ui")))
      ),
      
      conditionalPanel(
        condition = "input.datatype == 'h5'",
        ns = ns,
        tags$hr(),
        tags$h4("Cell Annotation Settings"),
        tags$p("Choose between marker-based fast annotation (scType) or reference-based accurate annotation (SingleR)."),
        selectInput(ns("annotation_method"), "Annotation Method", 
                    choices = c("scType (Marker-based)" = "sctype", "SingleR (Reference-based)" = "singler"), 
                    selected = "sctype"),
        conditionalPanel(
          condition = sprintf("input['%s'] == 'sctype'", ns("annotation_method")),
          selectInput(ns("sctype_tissue"), "Target Tissue (scType)",
                      choices = c("Immune system", "Pancreas", "Heart", "Brain", "Placenta", "Kidney", "Liver", "Lung", "Muscle", "Intestine"), 
                      selected = "Immune system")
        ),
        conditionalPanel(
          condition = sprintf("input['%s'] == 'singler'", ns("annotation_method")),
          selectInput(ns("singler_ref"), "Reference Dataset (celldex)",
                      choices = list(
                        "Human Primary Cell Atlas (Broad)" = "HumanPrimaryCellAtlasData",
                        "Monaco Immune Data (Immune)" = "MonacoImmuneData",
                        "Database of Immune Cell Expression (DICE)" = "DatabaseImmuneCellExpressionData",
                        "Novershtern Hematopoietic Data" = "NovershternHematopoieticData",
                        "Blueprint Encode Data" = "BlueprintEncodeData",
                        "Mouse RNA-seq Data (Broad)" = "MouseRNAseqData",
                        "ImmGen (Mouse Immune)" = "ImmGenData"
                      ), selected = "HumanPrimaryCellAtlasData")
        ),
        tags$hr(),
        tags$h4("Quality Control & Filtering (Optional)"),
        tags$p("Adjust the criteria to filter out low-quality cells or doublets."),
        fluidRow(
          column(6, numericInput(ns("min_features"), "Min Features (nFeature_RNA)", value = 200, min = 0, step = 50)),
          column(6, numericInput(ns("max_features"), "Max Features (nFeature_RNA)", value = 2500, min = 0, step = 50))
        ),
        fluidRow(
          column(6, numericInput(ns("min_count"), "Min Counts (nCount_RNA)", value = 0, min = 0, step = 100)),
          column(6, numericInput(ns("max_count"), "Max Counts (nCount_RNA)", value = 100000, min = 0, step = 100))
        ),
        fluidRow(
          column(6, numericInput(ns("max_mt"), "Max MT% (percent.mt)", value = 5, min = 0, max = 100, step = 1))
        ),
        tags$hr(),
        tags$h4("Data Integration (Optional)"),
        tags$p("If uploading multiple datasets or samples, run Harmony batch correction to align clusters."),
        checkboxInput(ns("run_harmony"), "Run Harmony Batch Correction (Group by 'sample' column)", value = FALSE)
      ),
      tags$hr(),
      
      # ### 変更点 ###
      # ボタンを"Run"の一つにまとめました
      fluidRow(
        column(3, actionButton(ns("run"), "Run", icon = icon("rocket"))),
        column(5,
               shinyjs::hidden(
                 downloadButton(ns("download_results"), "Download Results (.rds)")
               )
        )
      ),
      fluidRow(
        column(3, actionButton(ns("demo_run"), "Demo Data", icon = icon("database"), style = "margin-top: 5px; color: #fff; background-color: #337ab7; border-color: #2e6da4"))
      ),
      
      shinyjs::hidden(
        tags$div(id = ns("status_message"),
                 style = "margin-top: 15px; padding: 10px; border-radius: 5px; background-color: #f0f0f0;")
      )
    ),
    
    # Right Column for Dynamic QC Plots
    column(7,
      conditionalPanel(
        condition = "input.datatype == 'h5'",
        ns = ns,
        tags$div(
          style = "border: 0.5px solid #000; padding: 15px; background-color: #fafafa;",
          tags$h3("Dynamic Quality Control (QC) Preview"),
          tags$p("These plots are built automatically from the *raw* unloaded data of your .h5 file."),
          tags$p("Adjust the filtering thresholds on the left side to see which cells will be retained (indicated by ", tags$b("red dashed lines", style = "color: red;"), ")."),
          conditionalPanel(
            condition = "output.qc_vln_plot == null",
            ns = ns,
            tags$p(tags$i("Please upload a .h5 file (or click Demo Data) to generate QC plots...", style = "color: gray;"))
          ),
          uiOutput(ns("qc_cell_count_ui")),
          plotOutput(ns("qc_vln_plot"), height = "350px"),
          tags$div(style = "margin-top: 20px;"),
          plotOutput(ns("qc_scatter_plot"), height = "350px")
        )
      )
    )
  )
}

# ==============================================================================
# Server ロジック (修正版)
# ==============================================================================
uploadCellrangerServer <- function(id, myReactives) {
  moduleServer(id, function(input, output, session) {
    ns <- session$ns

    output$h5_status_ui <- renderUI({ req(input$h5); tags$p("✅ Uploaded!", style = "color: green;") })
    output$rds_status_ui <- renderUI({ req(input$rds); tags$p("✅ Uploaded!", style = "color: green;") })
    output$tcr_status_ui <- renderUI({ req(input$tcr); tags$p("✅ Uploaded!", style = "color: green;") })
    output$bcr_status_ui <- renderUI({ req(input$bcr); tags$p("✅ Uploaded!", style = "color: green;") })

    # -- Dynamic QC Preview Logic --
    # Notice we store it in myReactives to share with the main pipeline later to skip reloading!
    observeEvent(input$h5, {
        myReactives$is_demo <- FALSE
        req(input$h5$datapath)
        shinyjs::show("status_message")
        shinyjs::html(id = "status_message", html = "<p style='color: blue;'>Loading .h5 file for QC preview. This may take a moment...</p>")
        tryCatch({
          h5_data <- Seurat::Read10X_h5(input$h5$datapath)
          if (is.list(h5_data) && !is.data.frame(h5_data) && ("Gene Expression" %in% names(h5_data))) {
            h5_data <- h5_data[["Gene Expression"]]
          }
          raw_so <- Seurat::CreateSeuratObject(counts = h5_data, project = "QC_Preview")
          raw_so[["percent.mt"]] <- Seurat::PercentageFeatureSet(raw_so, pattern = "^MT-")
          
          # Assign to myReactives so we can render plots immediately and re-use later
          myReactives$raw_qc_seurat <- raw_so
          
          # Dynamically update the UI inputs to match the actual data boundaries!
          updateNumericInput(session, "min_features", value = min(raw_so$nFeature_RNA))
          updateNumericInput(session, "max_features", value = max(raw_so$nFeature_RNA))
          updateNumericInput(session, "min_count", value = min(raw_so$nCount_RNA))
          updateNumericInput(session, "max_count", value = max(raw_so$nCount_RNA))
          updateNumericInput(session, "max_mt", value = ceiling(max(raw_so$percent.mt)))
          
        }, error = function(e) {
          showNotification(paste("Error loading .h5:", e$message), type = "error")
        })
        shinyjs::hide("status_message")
    })
    
    # Observe Demo Data click to populate QC plots
    observeEvent(input$demo_run, {
        demo_h5 <- "example/230405_ruft_hcw_vaccine_merge_3000.h5"
        if(file.exists(demo_h5)) {
            shinyjs::show("status_message")
            shinyjs::html(id = "status_message", html = "<p style='color: blue;'>Loading Demo Data for QC preview... Please tune the parameters and click Run.</p>")
            
            # Setup demo state flag
            myReactives$is_demo <- TRUE
            
            h5_data <- Seurat::Read10X_h5(demo_h5)
            if (is.list(h5_data) && !is.data.frame(h5_data) && ("Gene Expression" %in% names(h5_data))) {
              h5_data <- h5_data[["Gene Expression"]]
            }
            raw_so <- Seurat::CreateSeuratObject(counts = h5_data, project = "QC_Preview_Demo")
            raw_so[["percent.mt"]] <- Seurat::PercentageFeatureSet(raw_so, pattern = "^MT-")
            myReactives$raw_qc_seurat <- raw_so
            
            # Dynamically update the UI inputs for demo data boundaries
            updateNumericInput(session, "min_features", value = min(raw_so$nFeature_RNA))
            updateNumericInput(session, "max_features", value = max(raw_so$nFeature_RNA))
            updateNumericInput(session, "min_count", value = min(raw_so$nCount_RNA))
            updateNumericInput(session, "max_count", value = max(raw_so$nCount_RNA))
            updateNumericInput(session, "max_mt", value = ceiling(max(raw_so$percent.mt)))
            
            updateRadioButtons(session, "datatype", selected = "h5")
            
            shinyjs::delay(4000, shinyjs::hide("status_message"))
        }
    })
    
    # Render Dynamic cell count UI
    output$qc_cell_count_ui <- renderUI({
      req(myReactives$raw_qc_seurat)
      so <- myReactives$raw_qc_seurat
      original_cells <- ncol(so)
      
      # Calculate remaining cells dynamically based on inputs
      filtered_cells <- sum(
        so$nFeature_RNA > input$min_features & 
        so$nFeature_RNA < input$max_features & 
        so$nCount_RNA > input$min_count &
        so$nCount_RNA < input$max_count &
        so$percent.mt < input$max_mt
      )
      
      tags$div(
        style = "margin-top: 10px; margin-bottom: 20px; padding: 15px; background-color: #e6f7ff; border-left: 5px solid #1890ff; border-radius: 4px;",
        tags$span(style = "font-size: 1.1em; font-weight: bold;", "Estimated Cells Remaining: "),
        tags$span(style = "color: #1890ff; font-size: 1.3em; font-weight: bold;", as.character(filtered_cells)),
        tags$span(style = "color: #555; font-size: 1.1em;", paste0(" / ", original_cells, " (", round(filtered_cells/original_cells*100, 1), "%)"))
      )
    })

    # Render QC Violin Plot
    output$qc_vln_plot <- renderPlot({
      req(myReactives$raw_qc_seurat)
      so <- myReactives$raw_qc_seurat
      
      p1 <- Seurat::VlnPlot(so, features = "nFeature_RNA", pt.size = 0.1) +
            ggplot2::geom_hline(yintercept = input$min_features, col = "red", linetype = "dashed", linewidth=1) + 
            ggplot2::geom_hline(yintercept = input$max_features, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::theme(legend.position = "none")
            
      p2 <- Seurat::VlnPlot(so, features = "nCount_RNA", pt.size = 0.1) +
            ggplot2::geom_hline(yintercept = input$min_count, col = "red", linetype = "dashed", linewidth=1) + 
            ggplot2::geom_hline(yintercept = input$max_count, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::theme(legend.position = "none")
            
      p3 <- Seurat::VlnPlot(so, features = "percent.mt", pt.size = 0.1) +
            ggplot2::geom_hline(yintercept = input$max_mt, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::theme(legend.position = "none")
      
      return(p1 | p2 | p3)
    })
    
    # Render QC Scatter Plot
    output$qc_scatter_plot <- renderPlot({
      req(myReactives$raw_qc_seurat)
      so <- myReactives$raw_qc_seurat
      
      p1 <- Seurat::FeatureScatter(so, feature1 = "nCount_RNA", feature2 = "percent.mt") +
            ggplot2::geom_hline(yintercept = input$max_mt, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::geom_vline(xintercept = input$min_count, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::geom_vline(xintercept = input$max_count, col = "red", linetype = "dashed", linewidth=1)
            
      p2 <- Seurat::FeatureScatter(so, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") +
            ggplot2::geom_hline(yintercept = input$min_features, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::geom_hline(yintercept = input$max_features, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::geom_vline(xintercept = input$min_count, col = "red", linetype = "dashed", linewidth=1) +
            ggplot2::geom_vline(xintercept = input$max_count, col = "red", linetype = "dashed", linewidth=1)
            
      return(p1 + p2)
    })

    # --- 共通解析ロジック関数 ---
    run_core_analysis_pipeline <- function() {
          if (myReactives$datatype == "h5") {
            # (2) .h5からSeuratオブジェクト作成
            incProgress(0.1, detail = "Loading .h5 file...")
            tmp_reactives <- h5_to_seurat_object(myReactives)
            for(n in names(tmp_reactives)) myReactives[[n]] <- tmp_reactives[[n]]
  
            # (3) Seurat標準解析 (Normalization, PCA, UMAP, etc.)
            incProgress(0.2, detail = "Running basic Seurat processing...")
            # Apply quality control filters set from UI
            tmp_reactives <- run_seurat_object(myReactives, 
                                               filter_min_feat = input$min_features, 
                                               filter_max_feat = input$max_features, 
                                               filter_min_count = input$min_count,
                                               filter_max_count = input$max_count,
                                               filter_max_mt   = input$max_mt,
                                               run_harmony     = input$run_harmony) 
            for(n in names(tmp_reactives)) myReactives[[n]] <- tmp_reactives[[n]]
  
            # (4) Automated Cell Annotation
            if (input$annotation_method == "sctype") {
              incProgress(0.1, detail = "Running scType cell typing...")
              message("--- Running scType analysis for tissue: ", input$sctype_tissue, " ---")
              myReactives$seurat_object <- run_sctype_and_update_seurat(myReactives$seurat_object, tissue = input$sctype_tissue)
            } else if (input$annotation_method == "singler") {
              incProgress(0.1, detail = "Running SingleR cell typing...")
              message("--- Running SingleR analysis using: ", input$singler_ref, " ---")
              myReactives$seurat_object <- run_singler_and_update_seurat(myReactives$seurat_object, ref_name = input$singler_ref)
            }
            myReactives$meta.data <- myReactives$seurat_object@meta.data
          } else if (myReactives$datatype == "rds") {
            # (2-4) ユーザーアップロードのSeuratオブジェクトを読み込む (前処理スキップ)
            incProgress(0.4, detail = "Loading pre-processed Seurat object...")
            message("--- Loading pre-processed RDS. Skipping Seurat normalizations and scType. ---")
            myReactives$seurat_object <- readRDS(myReactives$rds_path)
            
            # 安全のための最低限のメタデータ整理
            if(is.null(rownames(myReactives$seurat_object@meta.data))) {
              rownames(myReactives$seurat_object@meta.data) <- colnames(myReactives$seurat_object)
            }
            # サンプル列がなければ作成する
            if(!"sample" %in% colnames(myReactives$seurat_object@meta.data)) {
               myReactives$seurat_object$sample <- "Sample1"
            }
            myReactives$meta.data <- myReactives$seurat_object@meta.data
          }

          # (5) TCRデータ処理
          if (!is.null(myReactives$tcr_path)) {
            incProgress(0.1, detail = "Processing TCR data...")
            req(myReactives$seurat_object)
            myReactives$tcr_df <- tcr_csv_to_dataframe(myReactives$tcr_path)
            
            # Seuratメタデータとマージ
            seurat_barcodes <- rownames(myReactives$seurat_object@meta.data)
            myReactives$tcr_df <- myReactives$tcr_df %>%
              dplyr::filter(barcode %in% seurat_barcodes)
            
            metadata <- myReactives$seurat_object@meta.data %>%
              tibble::rownames_to_column(var = "barcode") %>% 
              dplyr::select(any_of(c("sample", "seurat_clusters")), barcode)
            myReactives$tcr_df <- dplyr::left_join(myReactives$tcr_df, metadata, by = "barcode")
            
            # 'tcr_status' 列をメタデータに追加
            message("--- Adding 'tcr_status' column to Seurat metadata ---")
            seurat_barcodes <- rownames(myReactives$seurat_object@meta.data)
            tcr_barcodes <- myReactives$tcr_df$barcode
            myReactives$seurat_object$tcr_status <- ifelse(seurat_barcodes %in% tcr_barcodes, "TCR positive", "TCR negative")
            
            # Extract and add Clone Size and Clone ID as metadata
            if ("raw_clonotype_id" %in% names(myReactives$tcr_df)) {
                clone_counts <- table(myReactives$tcr_df$raw_clonotype_id)
                tcr_sizes <- as.numeric(clone_counts[myReactives$tcr_df$raw_clonotype_id])
                
                size_map <- stats::setNames(tcr_sizes, myReactives$tcr_df$barcode)
                myReactives$seurat_object$TCR_cloneSize <- unname(size_map[seurat_barcodes])
                myReactives$seurat_object$TCR_cloneSize[is.na(myReactives$seurat_object$TCR_cloneSize)] <- 0
                
                id_map <- stats::setNames(myReactives$tcr_df$raw_clonotype_id, myReactives$tcr_df$barcode)
                myReactives$seurat_object$TCR_clonotype_id <- unname(id_map[seurat_barcodes])
                myReactives$seurat_object$TCR_clonotype_id[is.na(myReactives$seurat_object$TCR_clonotype_id)] <- "None"
            }
            
            message("'tcr_status' column added. Summary:")
            print(table(myReactives$seurat_object@meta.data$tcr_status))
          }

          # (6) BCRデータ処理
          if (!is.null(myReactives$bcr_path)) {
            incProgress(0.1, detail = "Processing BCR data...")
            req(myReactives$seurat_object)
            myReactives$bcr_df <- bcr_csv_to_dataframe(myReactives$bcr_path) # 修正: 正しい関数を呼び出す
            
            seurat_barcodes <- rownames(myReactives$seurat_object@meta.data)
            myReactives$bcr_df <- myReactives$bcr_df %>%
              dplyr::filter(barcode %in% seurat_barcodes)
              
            metadata <- myReactives$seurat_object@meta.data %>%
              tibble::rownames_to_column(var = "barcode") %>%
              dplyr::select(any_of(c("sample", "seurat_clusters")), barcode)
            myReactives$bcr_df <- dplyr::left_join(myReactives$bcr_df, metadata, by = "barcode")

            message("--- Adding 'bcr_status' column to Seurat metadata ---")
            seurat_barcodes <- rownames(myReactives$seurat_object@meta.data)
            bcr_barcodes <- myReactives$bcr_df$barcode
            myReactives$seurat_object$bcr_status <- ifelse(seurat_barcodes %in% bcr_barcodes, "BCR positive", "BCR negative")
            
            # Extract and add Clone Size and Clone ID as metadata
            if ("raw_clonotype_id" %in% names(myReactives$bcr_df)) {
                clone_counts <- table(myReactives$bcr_df$raw_clonotype_id)
                bcr_sizes <- as.numeric(clone_counts[myReactives$bcr_df$raw_clonotype_id])
                
                size_map <- stats::setNames(bcr_sizes, myReactives$bcr_df$barcode)
                myReactives$seurat_object$BCR_cloneSize <- unname(size_map[seurat_barcodes])
                myReactives$seurat_object$BCR_cloneSize[is.na(myReactives$seurat_object$BCR_cloneSize)] <- 0
                
                id_map <- stats::setNames(myReactives$bcr_df$raw_clonotype_id, myReactives$bcr_df$barcode)
                myReactives$seurat_object$BCR_clonotype_id <- unname(id_map[seurat_barcodes])
                myReactives$seurat_object$BCR_clonotype_id[is.na(myReactives$seurat_object$BCR_clonotype_id)] <- "None"
            }
            
            message("'bcr_status' column added. Summary:")
            print(table(myReactives$seurat_object@meta.data$bcr_status))
          }
          
          # (7) 解析結果をキャッシュとして保存
          incProgress(0.1, detail = "Finalizing and saving results to cache...")
          # demo_runの場合はキャッシュを上書きしない方が良いかもしれないが、
          # 仕様上「解析結果」は一つなので上書きされる。
          results_to_save <- reactiveValuesToList(myReactives)
          saveRDS(results_to_save, file = "analysis_cache.rds") # パスは共通
          message(paste("--- ✅ Analysis complete. Results saved to analysis_cache.rds ---"))
    }

    # [NOTE] Demo Data Run Event historically ran the pipeline automatically,
    # but has been heavily refactored to just map the demo data so we can use Dynamic QC. 
    # The actual pipeline trigger happens entirely via `input$run` now!
    observeEvent(input$run, {
      # --- 1. キャッシュファイルのパスを定義 ---
      cache_file_path <- "analysis_cache.rds"

      # --- 2. 入力とキャッシュの存在をチェック ---
      # キャッシュがなく、かつ.h5/.rdsファイルもアップロードされていない場合はエラー
      input_missing <- !isTRUE(myReactives$is_demo) && ((input$datatype == "h5" && is.null(input$h5$datapath)) || (input$datatype == "rds" && is.null(input$rds$datapath)))
      
      if (!file.exists(cache_file_path) && input_missing) {
        shinyalert::shinyalert("Input Required", "Please upload the primary input file (.h5 or .rds) for the first analysis.", type = "error")
        return()
      }

      # --- 3. UIの初期化 ---
      shinyjs::hide("download_results")
      shinyjs::disable("run")
      shinyjs::disable("demo_run")
      shinyjs::show("status_message")

      withProgress(message = 'Analysis in progress', value = 0, {
        # --- 4. キャッシュの読み込み、または新規解析の実行 ---
        
        if (file.exists(cache_file_path) && input_missing) {
          # --- [A] キャッシュが存在する場合：読み込んでスキップ ---
          shinyjs::html(id = "status_message", html = paste0("<p style='color: #8A2BE2;'>📁 Found '", cache_file_path, "'. Loading cached analysis results...</p>"))
          incProgress(0.2, detail = "Loading cached data...")

          # キャッシュファイルを読み込む
          cached_data <- readRDS(cache_file_path)

          # myReactivesの各項目を復元
          for (name in names(cached_data)) {
            myReactives[[name]] <- cached_data[[name]]
          }

          incProgress(0.8, detail = "Cached data loaded successfully.")
          message(paste("✅ Successfully loaded all analysis results from", cache_file_path))

        } else {
          # --- [B] キャッシュが存在しない場合：新規解析を実行 ---
          shinyjs::html(id = "status_message", html = "<p style='color: blue;'>🚀 Starting new analysis pipeline... (This may take a while)</p>")

          # (1) ファイルパスの割り当て
          incProgress(0.1, detail = "Assigning file paths...")
          
          if (!isTRUE(myReactives$is_demo)) {
            myReactives <- fileUpload(input, myReactives)  
          } else {
            myReactives$datatype <- "h5"
            myReactives$h5_path  <- "example/230405_ruft_hcw_vaccine_merge_3000.h5"
            myReactives$tcr_path <- "example/230405_ruft_hcw_vaccine_merge_3000_t.csv"
            myReactives$bcr_path <- "example/230405_ruft_hcw_vaccine_merge_3000_b.csv"
          }

          # 共通解析ロジック呼び出し
          tryCatch({
            run_core_analysis_pipeline()
          }, error = function(e) {
            message("Error in core analysis pipeline: ", e$message)
            shinyalert::shinyalert("Analysis Failed", paste("An error occurred during the analysis pipeline:", e$message), type = "error")
          })
          
        }
      }) # withProgressの終わり

      # --- 5. 完了処理 ---
      shinyjs::html(id = "status_message", html = "<p style='color: green;'>🎉 Analysis finished successfully!</p>")
      shinyjs::enable("run")
      shinyjs::enable("demo_run")
      shinyjs::show("download_results")
      shinyjs::delay(5000, shinyjs::hide("status_message"))
    })

    output$download_results <- downloadHandler(
      filename = function() {
        # 保存するファイル名をキャッシュファイル名と合わせる
        "analysis_cache.rds"
      },
      content = function(file) {
        # サーバー上に存在するキャッシュファイルをそのままコピーしてダウンロードさせる
        file.copy("analysis_cache.rds", file)
      }
    )

  })
}

# ==============================================================================
# scType 実行のためのヘルパー関数 (デバッグメッセージ付き)
# ==============================================================================
#' @title scType を実行し、Seuratオブジェクトを更新する
#' @description Seuratオブジェクトを受け取り、scTypeによるセルタイピングを実行し、
#'              結果をメタデータに `sctype_celltype` として追加します。
#' @param seurat_obj `Seurat` オブジェクト。
#' @return `Seurat` オブジェクト。メタデータにセルタイプ情報が追加されています。
run_sctype_and_update_seurat <- function(seurat_obj, tissue = "Immune system") {
 
  # ### 変更点 2: 各ステップに確認メッセージを追加 ###
  message("[scType Step 1/5] Preparing scripts and marker files...")
  
  # Ensure sctype_score.R is also downloaded and sourced
  sctype_score_url <- "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R"
  sctype_score_path <- "sctype_score_.R"
  if (!file.exists(sctype_score_path)) {
    download.file(sctype_score_url, sctype_score_path)
    message("Downloaded sctype_score_.R")
  }
  source(sctype_score_path)
  sctype_url <- "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R"
  sctype_script_path <- "gene_sets_prepare.R"
  if (!file.exists(sctype_script_path)) {
    download.file(sctype_url, sctype_script_path)
    message("Downloaded gene_sets_prepare.R")
  }
  
  db_url <- "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_short.xlsx"
  db_path <- "ScTypeDB_short.xlsx"
  if (!file.exists(db_path)) {
    download.file(db_url, db_path)
    message("Downloaded ScTypeDB_short.xlsx")
  }
  
  source(sctype_script_path)
  message("[scType Step 2/5] Loading gene sets database for '", tissue, "'...")
  # Suppress warnings from HGNChelper about non-approved gene symbols in the database
  suppressWarnings({
    gs_list <- gene_sets_prepare(db_path, tissue)
  })
  
  message("[scType Step 3/5] Performing scType scoring...")
  es.max <- sctype_score(
    scRNAseqData = GetAssayData(seurat_obj, assay = "RNA", layer = "data"),
    scaled = FALSE,
    gs = gs_list$gs_positive,
    gs2 = gs_list$gs_negative
  )
  message("Scoring completed. Dimension of score matrix: ", paste(dim(es.max), collapse = " x "))
  
  message("[scType Step 4/5] Identifying top cell types...")
  n_gs <- names(gs_list$gs_positive)
  es.max.cl <- apply(es.max, 2, function(x) {
    if (max(x) > 0) {
      n_gs[which.max(x)]
    } else {
      "Unknown"
    }
  })
  message("Cell types identified. First 6 results: ", paste(head(es.max.cl), collapse = ", "))
  
  message("[scType Step 5/5] Adding 'sctype_celltype' to metadata...")
  seurat_obj@meta.data$sctype_celltype <- es.max.cl
  
  # 最後の確認
  if("sctype_celltype" %in% colnames(seurat_obj@meta.data)){
      message("✅ Success! 'sctype_celltype' column was added to Seurat object metadata.")
  } else {
      message("❌ Failure! 'sctype_celltype' column was NOT added.")
  }
  
  return(seurat_obj)
}

#' @description Runs SingleR automated reference-based annotation.
run_singler_and_update_seurat <- function(seurat_obj, ref_name = "HumanPrimaryCellAtlasData") {
  message("[SingleR Step 1/3] Loading reference dataset: ", ref_name)
  if (!requireNamespace("SingleR", quietly = TRUE) || !requireNamespace("celldex", quietly = TRUE)) {
     warning("SingleR or celldex package is not installed. Please build v2.0 docker. Skipping annotation.")
     return(seurat_obj)
  }
  
  # Fetch reference data based on user selection
  ref_data <- switch(ref_name,
      "HumanPrimaryCellAtlasData" = celldex::HumanPrimaryCellAtlasData(),
      "MonacoImmuneData" = celldex::MonacoImmuneData(),
      "DatabaseImmuneCellExpressionData" = celldex::DatabaseImmuneCellExpressionData(),
      "NovershternHematopoieticData" = celldex::NovershternHematopoieticData(),
      "BlueprintEncodeData" = celldex::BlueprintEncodeData(),
      "MouseRNAseqData" = celldex::MouseRNAseqData(),
      "ImmGenData" = celldex::ImmGenData(),
      celldex::HumanPrimaryCellAtlasData() # Default
  )
  
  message("[SingleR Step 2/3] Extracting scRNA-seq counts and running SingleR...")
  # GetAssayData default layer is data (log-normalized)
  counts <- GetAssayData(seurat_obj, assay = "RNA", layer = "data")
  
  if ("seurat_clusters" %in% colnames(seurat_obj@meta.data)) {
      clusters <- seurat_obj$seurat_clusters
      message("Running SingleR by clusters for speed...")
      pred <- SingleR::SingleR(test = counts, ref = ref_data, labels = ref_data$label.fine, clusters = clusters)
      # Map back to single cells
      cell_labels <- pred$labels[match(as.character(clusters), rownames(pred))]
  } else {
      message("Running SingleR on individual cells (this may take longer)...")
      pred <- SingleR::SingleR(test = counts, ref = ref_data, labels = ref_data$label.fine)
      cell_labels <- pred$labels
  }
  
  message("[SingleR Step 3/3] Adding 'singler_celltype' to metadata...")
  seurat_obj@meta.data$singler_celltype <- cell_labels
  
  if("singler_celltype" %in% colnames(seurat_obj@meta.data)){
      message("✅ Success! 'singler_celltype' column was added to Seurat object metadata.")
  } else {
      message("❌ Failure! 'singler_celltype' column was NOT added.")
  }
  
  return(seurat_obj)
}

run_seurat_object <- function(myReactives, filter_min_feat = 200, filter_max_feat = 2500, filter_min_count = 0, filter_max_count = 100000, filter_max_mt = 5, run_harmony = FALSE) {
  req(myReactives$seurat_object)
  seurat_object <- myReactives$seurat_object
  
  tryCatch({
    message("--- [Seurat Process] Starting basic Seurat processing ---")
    
    # --- メタデータとQC、およびセルのフィルタリング ---
    message(paste0("[Seurat Process Step 1/7] Adding metadata, calculating MT%, and filtering cells (MinFeat:", filter_min_feat, " MaxFeat:", filter_max_feat, " MinCount:", filter_min_count, " MaxCount:", filter_max_count, " MaxMT:", filter_max_mt, ")..."))
    if(is.null(rownames(seurat_object@meta.data))) rownames(seurat_object@meta.data) <- colnames(seurat_object)
    seurat_object@meta.data <- seurat_object@meta.data %>%
      tibble::rownames_to_column("barcode") %>%
      mutate(sample = tryCatch(str_remove(barcode, "^.+-" ), error = function(e) { 
        warning("Could not extract sample from barcode."); NA_character_ 
      })) %>%
      tibble::column_to_rownames("barcode")
    seurat_object[["percent.mt"]] <- Seurat::PercentageFeatureSet(seurat_object, pattern = "^MT-")
    
    # Dynamic filtering cells (as requested by reviewers)
    seurat_object <- subset(seurat_object, subset = nFeature_RNA > filter_min_feat & nFeature_RNA < filter_max_feat & nCount_RNA > filter_min_count & nCount_RNA < filter_max_count & percent.mt < filter_max_mt)
    
    if (ncol(seurat_object) < 10) {
      stop("After filtering, too few cells (< 10) remained! Please check the QC preview plot and adjust your filtering thresholds (e.g. higher Max MT% or broader Feature limits).")
    }
    
    # 🌟 メモリ不足 (OOM 137 exit code) 対策： 重い処理に入る前に生データのゴミを強制解放
    gc()
    
    message("Completed metadata, QC, and cell filtering. Remaining cells: ", ncol(seurat_object))

    # --- 正規化 ---
    message("[Seurat Process Step 2/7] Normalizing data...")
    seurat_object <- Seurat::NormalizeData(seurat_object)
    message("Completed NormalizeData.")

    # --- 変動遺伝子の検出 ---
    message("[Seurat Process Step 3/7] Finding variable features...")
    seurat_object <- Seurat::FindVariableFeatures(seurat_object, selection.method = "vst", nfeatures = 2000)
    message("Completed FindVariableFeatures.")

    # --- スケーリング ---
    message("[Seurat Process Step 4/7] Scaling data...")
    # all.genes <- rownames(seurat_object)
    # seurat_object <- Seurat::ScaleData(seurat_object, features = all.genes)
    seurat_object <- Seurat::ScaleData(seurat_object)
    message("Completed ScaleData.")

    # --- PCA ---
    message("[Seurat Process Step 5/7] Running PCA...")
    npcs_to_compute <- min(50, ncol(seurat_object) - 1, nrow(seurat_object) - 1)
    seurat_object <- Seurat::RunPCA(seurat_object, features = Seurat::VariableFeatures(object = seurat_object), npcs = npcs_to_compute)
    # PCAの結果が存在するか確認
    if ("pca" %in% names(seurat_object@reductions)) {
      message("✅ RunPCA successful. PCA dimensions: ", paste(dim(seurat_object[['pca']]), collapse = " x "))
    } else {
      stop("❌ RunPCA failed. No 'pca' reduction found in the object.")
    }

    # --- Harmony Batch Correction ---
    reduction_use <- "pca"
    if (run_harmony) {
        message("[Seurat Process Optional] Running Harmony Batch Correction...")
        if (!requireNamespace("harmony", quietly = TRUE)) {
            warning("harmony package is not installed. Skipping Harmony.")
        } else {
            if (length(unique(seurat_object$sample)) > 1) {
                seurat_object <- harmony::RunHarmony(seurat_object, group.by.vars = "sample", reduction = "pca", assay.use = "RNA")
                if ("harmony" %in% names(seurat_object@reductions)) {
                    message("✅ RunHarmony successful.")
                    reduction_use <- "harmony"
                }
            } else {
                message("⚠️ Only 1 sample found. Skipping Harmony Batch Correction as it requires >= 2 samples.")
            }
        }
    }

    # --- UMAP & t-SNE ---
    dims_to_use <- 1:min(30, ncol(seurat_object[['pca']]))
    message("Using dimensions 1:", max(dims_to_use), " for UMAP and t-SNE based on reduction: ", reduction_use)
    
    message("[Seurat Process Step 6/7] Running UMAP...")
    seurat_object <- Seurat::RunUMAP(seurat_object, dims = dims_to_use, reduction = reduction_use)
    # UMAPの結果が存在するか確認
    if ("umap" %in% names(seurat_object@reductions)) {
      message("✅ RunUMAP successful.")
    } else {
      warning("❌ RunUMAP failed or did not complete. No 'umap' reduction found.")
    }

    message("[Seurat Process Step 7/7] Running t-SNE...")
    seurat_object <- Seurat::RunTSNE(seurat_object, dims = dims_to_use, reduction = reduction_use, check_duplicates = FALSE)
    # t-SNEの結果が存在するか確認
    if ("tsne" %in% names(seurat_object@reductions)) {
      message("✅ RunTSNE successful.")
    } else {
      warning("❌ RunTSNE failed or did not complete. No 'tsne' reduction found.")
    }
    
    # --- クラスタリング ---
    # UMAP/t-SNEの後でクラスタリングを実行
    message("[Seurat Process] Finding neighbors and clusters...")
    seurat_object <- Seurat::FindNeighbors(seurat_object, dims = dims_to_use, reduction = reduction_use)
    seurat_object <- Seurat::FindClusters(seurat_object, resolution = 0.5)
    message("Clustering complete.")

    myReactives$seurat_object <- seurat_object
    myReactives$meta.data <- seurat_object@meta.data
    # saveRDS(myReactives$seurat_object, 'seurat_object.rds') # 個別の保存は不要に
    
    message("--- [Seurat Process] All steps finished successfully! ---")
    
  }, error = function(e) {
    # エラーが発生した場合、コンソールに詳細なメッセージを表示
    message("!!!!!!!!!! Error in run_seurat_object !!!!!!!!!!")
    message("Error message: ", e$message)
    shinyalert::shinyalert("Seurat Processing Error", e$message, type = "error")
  })
  
  return(myReactives)
}

# この関数は変更なしでOKです！ (rds_pathも追加します)
fileUpload <- function(input, myReactives) {
  myReactives$datatype <- input$datatype
  myReactives$h5_path <- input$h5$datapath
  myReactives$rds_path <- input$rds$datapath
  myReactives$tcr_path <- input$tcr$datapath
  myReactives$bcr_path <- input$bcr$datapath
  return(myReactives)
}


# (パッケージとしてビルドする場合の推奨記述)
#' @importFrom dplyr %>% mutate case_when relocate starts_with coalesce across ends_with na_if select all_of any_of filter distinct full_join rename_with rename everything
#' @importFrom stringr str_c str_replace_all
#' @importFrom tidyselect everything
#' @importFrom readr read_csv
#' @importFrom scRepertoire combineTCR
#' @importFrom stats setNames
#' @importFrom rlang sym .data

# --- 定数定義 ---
PREFIX_TCR_PAIR  <- "TCR_pair_"
PREFIX_TCR_ALPHA <- "TCR_TRA_" # Alpha鎖 (TRA)
PREFIX_TCR_BETA  <- "TCR_TRB_" # Beta鎖 (TRB)

PREFIX_BCR_PAIR  <- "BCR_pair_" # Assuming this constant is needed for BCR processing


# --- ヘルパー関数定義 ---
# (csv_to_tcr_pair_dataframe, csv_to_tcr_tra_dataframe, csv_to_tcr_trb_dataframe, merge_tcr, paste_existing_cols は変更なし)
# (省略のため、ここでは再掲しません)
# --- (省略されたヘルパー関数) ---
#' @title CSVからTCRペア鎖データを抽出・整形
#' @description 指定されたCSVファイルからscRepertoire::combineTCRを使用して
#'              ペア鎖データ (主にTRA/TRB) を抽出し、整形します。
#'              同一barcodeに複数α/β鎖がある場合はフィルタリングします (filterMulti=TRUE)。
#' @param csv_path `character(1)`. 入力CSVファイルのパス。
#' @param sample_name `character(1)`. combineTCRで使用する一時的なサンプル名。デフォルトは "temp_sample"。
#' @param id_name `character(1)`. combineTCRで使用する一時的なID名。デフォルトは "temp_id"。
#' @return `data.frame`. 整形されたTCRペア鎖情報。列名は `PREFIX_TCR_PAIR` 付与。
csv_to_tcr_pair_dataframe <- function(csv_path,
                                      sample_name = "temp_sample",
                                      id_name = "temp_id") {

  barcode_prefix <- paste0(sample_name, "_", id_name, "_")
  tcr_raw <- tryCatch({
    readr::read_csv(csv_path, show_col_types = FALSE)
  }, error = function(e) {
    stop("Error reading CSV file: ", csv_path, "\n", e$message)
    return(NULL)
  })
  if (is.null(tcr_raw)) return(NULL)

  pair_list <- tryCatch({
    scRepertoire::combineTCR(tcr_raw, samples = sample_name, ID = id_name, filterMulti = TRUE, removeNA = TRUE)
  }, error = function(e) {
    stop("Error in combineTCR: ", e$message)
    return(NULL)
  })

  if (is.null(pair_list) || length(pair_list) == 0 || is.null(pair_list[[1]])) {
    warning("combineTCR did not return valid pair data.")
    return(data.frame()) # 空のデータフレームを返す
  }
  pair <- pair_list[[1]]

  pair <- pair %>%
    dplyr::mutate(barcode = stringr::str_replace_all(barcode, pattern = barcode_prefix, replacement = "")) %>%
    dplyr::select(-dplyr::any_of(c("sample", "ID"))) %>%
    dplyr::rename_with(~ stringr::str_c(PREFIX_TCR_PAIR, .), dplyr::everything())

  return(pair)
}

# Assuming csv_to_bcr_pair_dataframe exists in this file,
# analogous to csv_to_tcr_pair_dataframe, and contains the problematic call.
# The following is a hypothetical reconstruction to show the fix.
#' @title CSVからBCRペア鎖データを抽出・整形
#' @description 指定されたCSVファイルからscRepertoire::combineBCRを使用して
#'              ペア鎖データ (主にIGH/IGL/IGK) を抽出し、整形します。
#' @param csv_path `character(1)`. 入力CSVファイルのパス。
#' @param sample_name `character(1)`. combineBCRで使用する一時的なサンプル名。デフォルトは "temp_sample"。
#' @param id_name `character(1)`. combineBCRで使用する一時的なID名。デフォルトは "temp_id"。
#' @return `data.frame`. 整形されたBCRペア鎖情報。列名は `PREFIX_BCR_PAIR` 付与。
csv_to_bcr_pair_dataframe <- function(csv_path,
                                      sample_name = "temp_sample",
                                      id_name = "temp_id") {

  barcode_prefix <- paste0(sample_name, "_", id_name, "_")
  bcr_raw <- tryCatch({
    readr::read_csv(csv_path, show_col_types = FALSE)
  }, error = function(e) {
    stop("Error reading CSV file: ", csv_path, "\n", e$message)
    return(NULL)
  })
  if (is.null(bcr_raw)) return(NULL)

  pair_list <- tryCatch({
    # combineBCR does NOT have filterMulti = TRUE.
    scRepertoire::combineBCR(bcr_raw, samples = sample_name, ID = id_name, removeNA = TRUE)
  }, error = function(e) {
    stop("Error in combineBCR: ", e$message)
    return(NULL)
  })

  if (is.null(pair_list) || length(pair_list) == 0 || is.null(pair_list[[1]])) {
    warning("combineBCR did not return valid pair data.")
    return(data.frame()) 
  }
  pair <- pair_list[[1]]

  # --- 独自拡張: V-identity 等の重要情報を生データから復元 ---
  # combineBCRで消えてしまう可能性があるため、バーコードをキーに結合
  if ("v_identity" %in% names(bcr_raw)) {
    # barcode 列があることを確認 (CellRanger format)
    v_id_df <- bcr_raw %>%
      dplyr::filter(chain == "IGH") %>% # IGHのSHMを優先
      dplyr::distinct(barcode, .keep_all = TRUE) %>%
      dplyr::select(barcode, v_identity)
    
    # pair の barcode は prefix がついているので注意
    pair <- pair %>%
      dplyr::mutate(temp_barcode = stringr::str_replace_all(barcode, pattern = barcode_prefix, replacement = "")) %>%
      dplyr::left_join(v_id_df, by = c("temp_barcode" = "barcode")) %>%
      dplyr::select(-temp_barcode)
  }

  pair <- pair %>%
    dplyr::mutate(barcode = stringr::str_replace_all(barcode, pattern = barcode_prefix, replacement = "")) %>%
    dplyr::select(-dplyr::any_of(c("sample", "ID"))) %>%
    dplyr::rename_with(~ stringr::str_c(PREFIX_BCR_PAIR, .), dplyr::everything())

  return(pair)
}


#' @title CSVからTCR Alpha鎖(TRA)データを抽出・整形
#' @description 指定されたCSVファイルからTRA鎖のデータを抽出し、
#'              barcodeごとにユニークにして整形します。
#' @param csv_path `character(1)`. 入力CSVファイルのパス。
#' @return `data.frame`. 整形されたTCR TRA情報。列名は `PREFIX_TCR_ALPHA` 付与。
csv_to_tcr_tra_dataframe <- function(csv_path){

  tcr_raw <- tryCatch({
    readr::read_csv(csv_path, show_col_types = FALSE)
  }, error = function(e) {
    stop("Error reading CSV file: ", csv_path, "\n", e$message)
    return(NULL)
  })
  if (is.null(tcr_raw) || !"chain" %in% names(tcr_raw) || !"barcode" %in% names(tcr_raw)) {
    warning("CSV file must contain 'chain' and 'barcode' columns.")
    return(data.frame()) # エラーではなく空を返す
  }

  TRA <- tcr_raw %>%
    dplyr::filter(chain == 'TRA') %>%
    dplyr::distinct(barcode, .keep_all = TRUE) %>%
    dplyr::rename_with(~ stringr::str_c(PREFIX_TCR_ALPHA, .), dplyr::everything())

  return(TRA)
}

#' @title CSVからTCR Beta鎖(TRB)データを抽出・整形
#' @description 指定されたCSVファイルからTRB鎖のデータを抽出し、
#'              barcodeごとにユニークにして整形します。
#' @param csv_path `character(1)`. 入力CSVファイルのパス。
#' @return `data.frame`. 整形されたTCR TRB情報。列名は `PREFIX_TCR_BETA` 付与。
csv_to_tcr_trb_dataframe <- function(csv_path){

  tcr_raw <- tryCatch({
    readr::read_csv(csv_path, show_col_types = FALSE)
  }, error = function(e) {
    stop("Error reading CSV file: ", csv_path, "\n", e$message)
    return(NULL)
  })
  if (is.null(tcr_raw) || !"chain" %in% names(tcr_raw) || !"barcode" %in% names(tcr_raw)) {
    warning("CSV file must contain 'chain' and 'barcode' columns.")
    return(data.frame()) # エラーではなく空を返す
  }

  TRB <- tcr_raw %>%
    dplyr::filter(chain == 'TRB') %>%
    dplyr::distinct(barcode, .keep_all = TRUE) %>%
    dplyr::rename_with(~ stringr::str_c(PREFIX_TCR_BETA, .), dplyr::everything())

  return(TRB)
}

#' @title TCR各鎖データを結合
#' @description ペア鎖、Alpha鎖(TRA)、Beta鎖(TRB)のデータフレームをbarcodeをキーにして結合します。
#' @param pair `data.frame`. `csv_to_tcr_pair_dataframe` の出力。
#' @param TRA `data.frame`. `csv_to_tcr_tra_dataframe` の出力。
#' @param TRB `data.frame`. `csv_to_tcr_trb_dataframe` の出力。
#' @return `data.frame`. 結合されたTCRデータフレーム。
merge_tcr <- function(pair, TRA, TRB){

  pair_barcode_col <- paste0(PREFIX_TCR_PAIR, "barcode")
  tra_barcode_col  <- paste0(PREFIX_TCR_ALPHA, "barcode")
  trb_barcode_col  <- paste0(PREFIX_TCR_BETA, "barcode")

  # pair が空なら空を返す
  if (nrow(pair) == 0) {
      warning("Input 'pair' data frame is empty in merge_tcr. Returning empty data frame.")
      return(data.frame())
  }
  # TRA または TRB が空の場合でも結合は可能 (full_joinのため)
  if (nrow(TRA) == 0) warning("Input 'TRA' data frame is empty in merge_tcr.")
  if (nrow(TRB) == 0) warning("Input 'TRB' data frame is empty in merge_tcr.")


  tcr_merged <- dplyr::full_join(pair, TRA, by = stats::setNames(tra_barcode_col, pair_barcode_col))
  tcr_merged <- dplyr::full_join(tcr_merged, TRB, by = stats::setNames(trb_barcode_col, pair_barcode_col))

  return(tcr_merged)
}

#' @title 存在する列の値を連結する内部ヘルパー関数
#' @description データフレームと列名のベクトルを受け取り、存在する列の値を行ごとに連結。
#' @param df `data.frame`. 対象のデータフレーム。
#' @param cols `character`. 連結したい列名のベクトル。
#' @return `character`. 各行について連結された文字列ベクトル。
paste_existing_cols <- function(df, cols) {
  existing_cols <- intersect(cols, names(df))
  if (length(existing_cols) == 0) {
    return(rep(NA_character_, nrow(df)))
  }
  # apply を使うより rowwise + paste0/unite の方が dplyr 的かもしれないが、
  # NA処理を含めると apply の方が簡潔な場合もある
  apply(df[, existing_cols, drop = FALSE], 1, function(row_values) {
      # NA を空文字に変換してから結合
      row_values_no_na <- ifelse(is.na(row_values), "", row_values)
      paste0(row_values_no_na, collapse = "")
  })
}
# --- メイン関数定義 (修正版) ---

#' @title CSVからTCRデータを処理するメイン関数 (代表ID修正・ペア必須版)
#' @description 指定されたCSVファイルからTCRデータ (主にTRA/TRB) を読み込み、
#'              ペア鎖、Alpha鎖、Beta鎖に分割・整形した後、結合し、TRB鎖のIDを
#'              元に代表ID (`raw_clonotype_id` と `exact_subclonotype_id`) を格納し、
#'              全長配列を生成し、列順序を整え、barcode列名を変更します。
#'              `raw_consensus_id` は削除されます。
#'              `exact_subclonotype_id` は TRB の `raw_clonotype_id` と
#'              `exact_subclonotype_id` を `_` で連結した値になります。
#'              **最終的にTRA鎖とTRB鎖の両方が存在する行のみを保持します。**
#' @param csv_path `character(1)`. 入力CSVファイルのパス。
#' @return `data.frame`. 全ての処理が完了し、TRA/TRBペアが存在する行のみを含むTCRデータフレーム。
#'         処理中にエラーが発生した場合や、有効なペアデータが見つからない場合は、
#'         空のデータフレームまたは警告付きの部分的な結果を返すことがあります。
tcr_csv_to_dataframe <- function(csv_path){

  # --- 1. 入力チェック ---
  if (!file.exists(csv_path)) {
    stop("Input CSV file not found: ", csv_path)
    return(NULL)
  }

  # --- 2. データ抽出・整形 ---
  pair_data <- csv_to_tcr_pair_dataframe(csv_path)
  tra_data  <- csv_to_tcr_tra_dataframe(csv_path)
  trb_data  <- csv_to_tcr_trb_dataframe(csv_path)

  if (is.null(pair_data) || nrow(pair_data) == 0 || !paste0(PREFIX_TCR_PAIR, "barcode") %in% names(pair_data)) {
      warning("No valid paired TCR data found or extracted. Returning an empty data frame.")
      return(data.frame())
  }
  if (is.null(tra_data) || nrow(tra_data) == 0) {
      warning("No TRA data extracted. Final result might be empty after filtering.")
  }
  if (is.null(trb_data) || nrow(trb_data) == 0) {
      warning("No TRB data extracted. Final result might be empty after filtering.")
  }

  # --- 3. データ結合 ---
  merged_df <- merge_tcr(pair_data, tra_data, trb_data)

  pair_barcode_col_check <- paste0(PREFIX_TCR_PAIR, "barcode")
  if (nrow(merged_df) == 0 || !pair_barcode_col_check %in% names(merged_df)) {
    warning("Merging TCR data resulted in an empty data frame or missing key barcode column. Returning the empty frame.")
    return(merged_df)
  }

  # --- 4. 代表ID生成と不要列削除 (★修正箇所★) ---
  # TRB鎖のIDを元に代表IDを生成
  trb_clonotype_col <- paste0(PREFIX_TCR_BETA, "raw_clonotype_id")
  trb_subclonotype_col <- paste0(PREFIX_TCR_BETA, "exact_subclonotype_id")
  # raw_consensus_id はここで生成しない

  # 削除対象の元のID列名 (TRA, TRB, Pair) - consensusも含む
  cols_to_remove <- c(
    paste0(PREFIX_TCR_ALPHA, c("raw_clonotype_id", "raw_consensus_id", "exact_subclonotype_id")),
    paste0(PREFIX_TCR_BETA, c("raw_clonotype_id", "raw_consensus_id", "exact_subclonotype_id")),
    paste0(PREFIX_TCR_PAIR, c("raw_clonotype_id", "raw_consensus_id", "exact_subclonotype_id"))
  )
  # データフレームに実際に存在する列のみを削除対象とする
  cols_to_remove_existing <- intersect(cols_to_remove, names(merged_df))

  processed_df <- merged_df %>%
    dplyr::mutate(
      # raw_clonotype_id は TRB由来のものをそのまま使用
      raw_clonotype_id = if (trb_clonotype_col %in% names(.)) .data[[trb_clonotype_col]] else NA_character_,
      # exact_subclonotype_id は TRB由来の raw_clonotype_id と exact_subclonotype_id を連結
      exact_subclonotype_id = dplyr::case_when(
        # 両方の列が存在し、かつ両方の値が NA でない場合のみ連結
        trb_clonotype_col %in% names(.) & trb_subclonotype_col %in% names(.) &
          !is.na(.data[[trb_clonotype_col]]) & !is.na(.data[[trb_subclonotype_col]])
          ~ stringr::str_c(.data[[trb_clonotype_col]], .data[[trb_subclonotype_col]], sep = "_"),
        # それ以外の場合は NA
        TRUE ~ NA_character_
      )
      # raw_consensus_id はここで生成しない
    ) %>%
    # 不要になった元のTRA/TRB/PairのID列(+ consensus 列)を削除
    dplyr::select(-dplyr::any_of(cols_to_remove_existing)) %>%
    # もしマージや他の処理で raw_consensus_id 列が残ってしまった場合に備えて明示的に削除
    dplyr::select(-dplyr::any_of("raw_consensus_id"))


  # --- 5. 列順序の整理 (★修正箇所★) ---
  # 代表ID列、ペア列、Alpha列、Beta列の順に並べ替え (consensus を除外)
  processed_df <- processed_df %>%
    dplyr::relocate(
      # 代表ID列を先頭に (raw_consensus_id を除外)
      dplyr::any_of(c("raw_clonotype_id", "exact_subclonotype_id")),
      # 次に各プレフィックスを持つ列
      dplyr::starts_with(PREFIX_TCR_PAIR),
      dplyr::starts_with(PREFIX_TCR_ALPHA),
      dplyr::starts_with(PREFIX_TCR_BETA),
      .before = tidyselect::everything() # その他の列の前に配置
    )

  # --- 6. 全長配列の生成 ---
  regions_nt <- c("fwr1_nt", "cdr1_nt", "fwr2_nt", "cdr2_nt", "fwr3_nt", "cdr3_nt", "fwr4_nt")
  regions_aa <- c("fwr1", "cdr1", "fwr2", "cdr2", "fwr3", "cdr3", "fwr4")

  tra_nt_cols <- paste0(PREFIX_TCR_ALPHA, regions_nt)
  trb_nt_cols <- paste0(PREFIX_TCR_BETA, regions_nt)
  tra_aa_cols <- paste0(PREFIX_TCR_ALPHA, regions_aa)
  trb_aa_cols <- paste0(PREFIX_TCR_BETA, regions_aa)

  processed_df <- processed_df %>%
    dplyr::mutate(
      !!paste0(PREFIX_TCR_ALPHA, "full_length_nt") := paste_existing_cols(., tra_nt_cols),
      !!paste0(PREFIX_TCR_BETA, "full_length_nt") := paste_existing_cols(., trb_nt_cols),
      !!paste0(PREFIX_TCR_ALPHA, "full_length_aa") := paste_existing_cols(., tra_aa_cols),
      !!paste0(PREFIX_TCR_BETA, "full_length_aa") := paste_existing_cols(., trb_aa_cols)
    ) %>%
    dplyr::mutate(
      dplyr::across(
        dplyr::ends_with("full_length_nt") | dplyr::ends_with("full_length_aa"),
        ~ dplyr::na_if(., "")
      )
    )

  # --- 7. 最終的な列整理 (barcode) ---
  pair_barcode_col_rename <- paste0(PREFIX_TCR_PAIR, "barcode")
  if (!"barcode" %in% names(processed_df) && pair_barcode_col_rename %in% names(processed_df)) {
    processed_df <- processed_df %>%
      dplyr::rename(barcode = !!rlang::sym(pair_barcode_col_rename))
  } else if (!"barcode" %in% names(processed_df)) {
      warning(paste("Column", pair_barcode_col_rename, "not found for renaming and 'barcode' column also does not exist."))
  }

  if ("barcode" %in% names(processed_df)) {
    processed_df <- processed_df %>% dplyr::relocate(barcode)
  }

  # --- 8. TRA/TRBペアが存在する行のみフィルタリング ---
  tra_key_col <- paste0(PREFIX_TCR_ALPHA, "chain")
  trb_key_col <- paste0(PREFIX_TCR_BETA, "chain")

  if (tra_key_col %in% names(processed_df) && trb_key_col %in% names(processed_df)) {
      final_df <- processed_df %>%
          dplyr::filter(!is.na(.data[[tra_key_col]]) & !is.na(.data[[trb_key_col]]))

      if(nrow(final_df) == 0 && nrow(processed_df) > 0) {
          warning("Filtering removed all rows. No barcodes with both TRA and TRB chains found after merging.")
      }

  } else {
      missing_cols <- c()
      if (!tra_key_col %in% names(processed_df)) missing_cols <- c(missing_cols, tra_key_col)
      if (!trb_key_col %in% names(processed_df)) missing_cols <- c(missing_cols, trb_key_col)
      warning(paste("Key columns for filtering (", paste(missing_cols, collapse=", "), ") not found in the merged data frame. Skipping the final filtering step."))
      final_df <- processed_df
  }

  # --- 9. 結果を返す ---
  return(final_df)
}

#' @title CSVからBCRデータを処理するメイン関数
#' @description 指定されたCSVファイルからBCRデータを読み込み、
#'              ペア鎖データを抽出・整形します。
#'              最終的にbarcode列をリネームし、先頭に移動させます。
#' @param csv_path `character(1)`. 入力CSVファイルのパス。
#' @return `data.frame`. 処理が完了したBCRデータフレーム。
#'         処理中にエラーが発生した場合や、有効なデータが見つからない場合は、
#'         空のデータフレームを返すことがあります。
bcr_csv_to_dataframe <- function(csv_path) {
  # --- 1. 入力チェック ---
  if (!file.exists(csv_path)) {
    stop("Input CSV file not found: ", csv_path)
    return(NULL)
  }

  # --- 2. データ抽出・整形 ---
  pair_data <- csv_to_bcr_pair_dataframe(csv_path)

  if (is.null(pair_data) || nrow(pair_data) == 0 || !paste0(PREFIX_BCR_PAIR, "barcode") %in% names(pair_data)) {
      warning("No valid paired BCR data found or extracted. Returning an empty data frame.")
      return(data.frame())
  }

  # --- 3. 最終的な列整理 (barcode) ---
  pair_barcode_col_rename <- paste0(PREFIX_BCR_PAIR, "barcode")
  if (!"barcode" %in% names(pair_data) && pair_barcode_col_rename %in% names(pair_data)) {
    processed_df <- pair_data %>%
      dplyr::rename(barcode = !!rlang::sym(pair_barcode_col_rename))
  } else if (!"barcode" %in% names(pair_data)) {
      warning(paste("Column", pair_barcode_col_rename, "not found for renaming and 'barcode' column also does not exist."))
      processed_df <- pair_data
  } else {
    processed_df <- pair_data
  }

  if ("barcode" %in% names(processed_df)) {
    processed_df <- processed_df %>% dplyr::relocate(barcode)
  }

  # Relocate v_identity if exists
  v_id_col <- paste0(PREFIX_BCR_PAIR, "v_identity")
  if (v_id_col %in% names(processed_df)) {
    processed_df <- processed_df %>% dplyr::relocate(!!rlang::sym(v_id_col), .after = barcode)
  }

  # --- 4. 結果を返す ---
  return(processed_df)
}


# ★ addCelltype は外部スクリプトに依存するため注意が必要 ★
addCelltype <- function(myReactives) {
  req(myReactives$seurat_object)

  # --- 1. 実行前のメタデータ列名を取得 ---
  original_cols <- colnames(myReactives$seurat_object@meta.data)

  # --- 2. sctypeの実行 ---
  # 外部スクリプトの読み込みと実行
  tryCatch({
    # local=TRUE で現在の環境に関数を読み込む
    source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_wrapper.R", local = TRUE)

    if (exists("run_sctype", mode = "function")) {
      # sctypeのパラメータを定義
      sctype_name_param <- "sctype_classification"
      sctype_tissue_param <- "Immune system" # Note: If you want to make this dynamic, pass it from myReactives

      # sctypeを実行
      myReactives$seurat_object <- run_sctype(
        myReactives$seurat_object,
        assay = "RNA",
        scaled = TRUE,
        known_tissue_type = sctype_tissue_param,
        custom_marker_file = "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_short.xlsx",
        name = sctype_name_param
      )

      # --- 3. 追加された列を特定し、リネーム ---
      new_cols <- colnames(myReactives$seurat_object@meta.data)
      added_cols <- setdiff(new_cols, original_cols)

      # sctypeが一時的に追加する可能性のある 'cluster' 列を除外
      sctype_result_col <- setdiff(added_cols, "cluster")

      # 結果列が1つだけ追加されたことを確認
      if (length(sctype_result_col) == 1) {
        # 実際に追加された列を 'Celltype' にリネーム
        myReactives$seurat_object@meta.data <- myReactives$seurat_object@meta.data %>%
          dplyr::rename(Celltype = !!rlang::sym(sctype_result_col))
        message("Successfully renamed column '", sctype_result_col, "' to 'Celltype'.")
      } else if (length(sctype_result_col) > 1) {
        warning("sctype added multiple unexpected columns: ", paste(sctype_result_col, collapse = ", "), ". Could not reliably determine which to rename to 'Celltype'.")
      } else {
        # 予測していた列名も警告に含める
        expected_col_name_raw <- paste0(sctype_name_param, "_", sctype_tissue_param)
        expected_col_name_clean <- make.names(expected_col_name_raw)
        warning("Could not find the sctype result column. Expected something like '", expected_col_name_clean, "' but found these new columns: ", paste(added_cols, collapse = ", "))
      }

      # --- 4. 不要な一時列を削除 ---
      # sctype_wrapper.R は 'cluster' という列を追加することがあります。
      # 以前はこの関数内で削除していましたが、後続のUI更新処理が
      # この'cluster'列の存在を前提としてエラーになる可能性があるため、
      # ここでは削除しないように変更します。後続の処理で不要な列として扱われることを想定しています。
      # if ("cluster" %in% added_cols) {
      #   myReactives$seurat_object@meta.data$cluster <- NULL
      # }
    } else {
      warning("run_sctype function not found after sourcing script.")
    }
  }, error = function(e) {
    warning("Failed to source or run sctype: ", e$message)
  })
  return(myReactives)
}