services:
  sicr-app:
    build:
      context: .
      # build_and_run.sh で設定された環境変数 DOCKERFILE_NAME を参照
      # 未設定の場合は Dockerfile をデフォルトとして使用
      dockerfile: ${DOCKERFILE_NAME:-Dockerfile}
    container_name: sicr-shiny-app
    platform: linux/amd64  # この行を確認・追加・有効化してください
    ports:
      - "3838:3838"
    volumes:
      # アプリケーションのサブディレクトリ sicr にマウント
      - ./data:/srv/shiny-server/sicr/data
      - ./example:/srv/shiny-server/sicr/example
      - shiny-logs:/var/log/shiny-server
    environment:
      - SHINY_LOG_LEVEL=INFO
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  shiny-logs:
